In [8]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt

In [9]:
df=pd.read_excel("../data/processed/Características y composición del hogar.xlsx")

Borramos los exactos duplicados.

In [10]:
df.drop_duplicates()

,DIRECTORIO,SECUENCIA_ENCUESTA,SECUENCIA_P,ORDEN,FEX_C,P6016,P1894,P6020,P6034,P6040,...,P1898,P1899,P3175,P1901,P1903,P1904,P1905,P1927,P3038,P3039
0,8369550,1,1,1,472.131901,1,3,2,1,45,...,10.0,5.0,7.0,10.0,6.0,0.0,7.0,6.0,1.0,2.0
1,8369550,2,1,2,472.131901,2,3,1,1,25,...,10.0,8.0,7.0,10.0,0.0,0.0,8.0,8.0,2.0,1.0
2,8369550,3,1,3,472.131901,3,2,2,1,16,...,10.0,10.0,10.0,10.0,0.0,0.0,10.0,10.0,NaN,NaN
3,8369550,4,1,4,472.131901,4,2,1,1,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,8369551,1,1,1,308.854319,1,3,2,1,62,...,7.0,4.0,7.0,8.0,6.0,2.0,8.0,7.0,1.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235345,8489520,2,1,2,19.043528,2,3,2,1,31,...,10.0,10.0,10.0,10.0,1.0,0.0,9.0,9.0,1.0,2.0
235346,8489520,3,1,3,19.043528,3,1,2,1,8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
235347,8489521,1,1,1,19.043528,1,3,1,1,31,...,10.0,9.0,9.0,10.0,1.0,0.0,10.0,9.0,2.0,1.0
235348,8489521,2,1,2,19.043528,2,3,2,1,32,...,10.0,10.0,9.0,9.0,1.0,1.0,10.0,9.0,1.0,2.0
235349,8489522,1,1,1,10.351017,1,3,1,1,45,...,8.0,8.0,8.0,8.0,1.0,0.0,10.0,6.0,2.0,1.0

Para las variables seleccionadas, evalúen la calidad de los datos. Identifiquen cuántos valores faltantes o nulos presenta cada variable y qué proporción representan respecto al total de registros.

hacemos un nuevo df unicamente con las variable que usamos.

In [11]:
df_variables=df[["P6040","P756","P756S1","P756S2","P756S3","P1895","P1896","P1897","P1898","P1899","P3175"]]
df_variables

,P6040,P756,P756S1,P756S2,P756S3,P1895,P1896,P1897,P1898,P1899,P3175
0,45,1,NaN,NaN,NaN,8.0,99.0,10.0,10.0,5.0,7.0
1,25,1,NaN,NaN,NaN,10.0,8.0,10.0,10.0,8.0,7.0
2,16,1,NaN,NaN,NaN,10.0,99.0,10.0,10.0,10.0,10.0
3,10,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,62,2,13.0,13433.0,NaN,5.0,4.0,7.0,7.0,4.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...
235345,31,1,NaN,NaN,NaN,10.0,10.0,10.0,10.0,10.0,10.0
235346,8,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
235347,31,1,NaN,NaN,NaN,10.0,10.0,10.0,10.0,9.0,9.0
235348,32,1,NaN,NaN,NaN,10.0,10.0,9.0,10.0,10.0,9.0
235349,45,1,NaN,NaN,NaN,8.0,8.0,8.0,8.0,8.0,8.0

Filtramos con la variable que nos dice la edad de cada encuestado para solo tener en cuenta aquellos mayores a 18.

In [12]:
df_variables.query("P6040>=18")

,P6040,P756,P756S1,P756S2,P756S3,P1895,P1896,P1897,P1898,P1899,P3175
0,45,1,NaN,NaN,NaN,8.0,99.0,10.0,10.0,5.0,7.0
1,25,1,NaN,NaN,NaN,10.0,8.0,10.0,10.0,8.0,7.0
4,62,2,13.0,13433.0,NaN,5.0,4.0,7.0,7.0,4.0,7.0
5,38,1,NaN,NaN,NaN,8.0,8.0,8.0,5.0,8.0,8.0
6,49,1,NaN,NaN,NaN,8.0,9.0,8.0,5.0,8.0,8.0
...,...,...,...,...,...,...,...,...,...,...,...
235344,32,1,NaN,NaN,NaN,9.0,9.0,9.0,10.0,10.0,9.0
235345,31,1,NaN,NaN,NaN,10.0,10.0,10.0,10.0,10.0,10.0
235347,31,1,NaN,NaN,NaN,10.0,10.0,10.0,10.0,9.0,9.0
235348,32,1,NaN,NaN,NaN,10.0,10.0,9.0,10.0,10.0,9.0
235349,45,1,NaN,NaN,NaN,8.0,8.0,8.0,8.0,8.0,8.0

Conocemos los porcentajes de valores nulos para cada variable.

In [13]:
(df_variables.isna().mean()*100).sort_values(ascending=False)

P756S3    96.576163
P756S2    66.427448
P756S1    66.427448
P1897     22.052263
P1898     22.052263
P1895     22.052263
P1896     22.052263
P1899     22.052263
P3175     22.052263
P756       0.000000
P6040      0.000000
dtype: float64

Cambiamos NaN que puedan ser reemplazados por No aplica

In [14]:
df_variables.dtypes

P6040       int64
P756        int64
P756S1    float64
P756S2    float64
P756S3    float64
P1895     float64
P1896     float64
P1897     float64
P1898     float64
P1899     float64
P3175     float64
dtype: object

## Analisis descriptivo